config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'surveys#index'
  
  resources :surveys do
    resources :questions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 100

  before_save(:titleize_survey)

  private
    def titleize_survey
      self.name = self.name.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    # binding.pry
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new
    render :new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.new(question_params)
    if @question.save
      redirect_to survey_path(@survey)
    else
      render :new
    end
  end

  def show
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :show
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to survey_path(@question.survey)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to survey_path(@question.survey)
  end

  private
    def question_params
      params.require(:question).permit(:query, :response)
    end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
    render :index
  end

  def new
    @survey = Survey.new
    render :new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to surveys_path
    else
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id].to_i)
    render :edit
  end

  def show
    # binding.pry
    @survey = Survey.find(params[:id].to_i)
    render :show
  end

  def update
    @survey = Survey.find(params[:id].to_i)
    if @survey.update(survey_params)
      redirect_to surveys_path
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id].to_i)
    @survey.destroy
    redirect_to surveys_path
  end

  private
    def survey_params
      params.require(:survey).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_survey_form.html.erb
<%= render "layouts/errors", :object => @survey %>

<%= form_for @survey do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit question:</h1>

<%= form_for [@survey, @question] do |f| %>
  <%= f.label :query %>
  <%= f.text_field :query %>
  <%= f.label :response %>
  <%= f.text_area :response %>
  <p><%= f.submit %></p>
<% end %>

app/views/questions/new.html.erb
<h1>New question:</h1>

<%= form_for [@survey, @question] do |f| %>
  <%= f.label :query %>
  <%= f.text_field :query %>
  <%= f.label :response %>
  <%= f.text_area :response %>
  <p><%= f.submit %></p>
<% end %>

app/views/questions/show.html.erb
<h1>Question: <%= @question.query %></h1>
<h2>Survey: <%= @survey.name %></h2>
<h3><%= @question.query %></h3>
<h3><%= @question.response %></h3>


<p><%= link_to "Edit question", edit_survey_question_path(@survey, @question) %></p>
<p><%= link_to "Delete question", survey_question_path(@survey, @question),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to survey", survey_path(@survey) %></p>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% if @surveys.any? %>
  <ul>
    <% @surveys.each do |survey| %>
      <li><%= link_to survey.name, survey_path(survey) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no surveys yet.</p>
<% end %>


<p><%= link_to "Create new survey", new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "layouts/survey_form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<% if @survey.questions.any? %>
  <h4>Here are the questions for this survey:</h4>

  <% @survey.questions.each do |question| %>
    <ul>
      <li>
        <%= link_to question.query, survey_question_path(@survey, question) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No questions are listed for this survey.</p>
<% end %>

<p><%= link_to "Add a question", new_survey_question_path(@survey) %></p>

<p><%= link_to "Edit", edit_survey_path(@survey) %></p>
<p><%= link_to "Delete survey", survey_path(@survey),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to surveys", surveys_path %></p>